# Generated by Django 4.0.6 on 2022-07-21 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 2, 26, 5, 716742), verbose_name='update_time'),
        ),
    ]
