# Generated by Django 4.0.6 on 2022-07-23 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_alter_notification_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 16, 12, 39, 422823), verbose_name='update_time'),
        ),
    ]
