# Generated by Django 4.0.6 on 2022-07-23 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_alter_notification_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 16, 26, 13, 161556), verbose_name='update_time'),
        ),
    ]
