# Generated by Django 4.0.6 on 2022-07-23 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_alter_notification_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='update_time',
            field=models.TextField(default=datetime.datetime(2022, 7, 23, 16, 43, 43, 343495), verbose_name='update_time'),
        ),
    ]
