# Generated by Django 4.0.6 on 2022-07-24 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_alter_friend_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='update_time',
            field=models.TextField(default=datetime.datetime(2022, 7, 24, 21, 46, 43, 446733), verbose_name='update_time'),
        ),
    ]
