# Generated by Django 4.0.6 on 2022-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('email', models.TextField(verbose_name='email')),
                ('nickname', models.CharField(max_length=32, verbose_name='nickname')),
                ('player_timezone', models.TextField(verbose_name='timezone')),
                ('model_3dnum', models.IntegerField(verbose_name='model3D')),
                ('player_last_uptime', models.DateTimeField(auto_now_add=True, verbose_name='recentaccess')),
                ('main_mission', models.IntegerField(verbose_name='mainmission')),
                ('sub_mission', models.TextField(verbose_name='submission')),
                ('last_pos', models.TextField(verbose_name='lastlocation')),
                ('last_city', models.TextField(verbose_name='lastcity')),
                ('balance', models.IntegerField(verbose_name='balance')),
                ('badge_state', models.IntegerField(verbose_name='BadgeInfo')),
                ('license_state', models.IntegerField(verbose_name='LicenseInfo')),
                ('update_time', models.DateTimeField(verbose_name='recentupdate')),
                ('inventory', models.TextField(verbose_name='Inventory')),
                ('import_info', models.TextField(verbose_name='importinfo')),
                ('export_info', models.TextField(verbose_name='exportinfo')),
                ('energy_import', models.TextField(verbose_name='energyinfo')),
                ('vechile_unlock', models.IntegerField(verbose_name='vechileInfo')),
                ('fuel_info', models.TextField(verbose_name='fuelInfo')),
            ],
            options={
                'db_table': 'user_db',
            },
        ),
    ]
