# Generated by Django 4.0.6 on 2022-07-17 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_player_last_uptime_alter_user_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='player_last_uptime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 22, 17, 35, 797994), verbose_name='recentaccess'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 17, 22, 17, 35, 798276), verbose_name='recentupdate'),
        ),
    ]
