# Generated by Django 4.0.6 on 2022-07-20 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_player_last_uptime_alter_user_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='model_3dnum',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='player_last_uptime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 15, 58, 37, 291943), verbose_name='recentaccess'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 15, 58, 37, 292039), verbose_name='recentupdate'),
        ),
    ]
