# Generated by Django 4.0.6 on 2022-07-20 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_model_3dnum_user_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vechile_unlock',
            new_name='vehicle_unlock',
        ),
        migrations.AlterField(
            model_name='user',
            name='player_last_uptime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 16, 0, 25, 610789), verbose_name='recentaccess'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 16, 0, 25, 610900), verbose_name='recentupdate'),
        ),
    ]
