# Generated by Django 4.0.6 on 2022-07-20 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_vechile_unlock_user_vehicle_unlock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='main_mission',
            new_name='main_misson',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sub_mission',
            new_name='sub_misson',
        ),
        migrations.AlterField(
            model_name='user',
            name='player_last_uptime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 16, 1, 41, 888280), verbose_name='recentaccess'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 16, 1, 41, 888389), verbose_name='recentupdate'),
        ),
    ]
