# Generated by Django 4.0.6 on 2022-07-21 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_player_last_uptime_alter_user_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='player_last_uptime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 17, 52, 3, 63056), verbose_name='recentaccess'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 17, 52, 3, 63165), verbose_name='recentupdate'),
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('traffic_hub_unlock', models.IntegerField(default=0, verbose_name='traffic_hub_unlock')),
                ('factory_level', models.IntegerField(default=0, verbose_name='factory_level')),
                ('factory_info', models.TextField(blank=True, verbose_name='factory_info')),
                ('elec_factory_unlock', models.IntegerField(default=0, verbose_name='elec_factory_unlock')),
                ('elec_factory_info', models.TextField(blank=True, verbose_name='elec_factory_info')),
                ('power_plant_unlock', models.IntegerField(default=0, verbose_name='power_plant_unlock')),
                ('ess_info', models.IntegerField(default=0, verbose_name='ess_info')),
                ('buttiport_unlock', models.IntegerField(default=0, verbose_name='buttiport_unlock')),
                ('subsidy_info', models.TextField(verbose_name='subsidy_info')),
                ('deco_item_position', models.TextField(blank=True, verbose_name='deco_item_position')),
                ('sewerage_unlock', models.IntegerField(default=0, verbose_name='sewerage_unlock')),
                ('fiber_machine_unlock', models.IntegerField(default=0, verbose_name='fiber_machine_unlock')),
                ('furnace_unlock', models.IntegerField(default=0, verbose_name='furnace_unlock')),
                ('furnace_info', models.TextField(blank=True, verbose_name='furnace_info')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='accounts.user', verbose_name='person_id')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('population', models.IntegerField(default=0, verbose_name='population')),
                ('happy_index', models.IntegerField(default=0, verbose_name='happy_index')),
                ('eco_elec_energy_index', models.IntegerField(default=0, verbose_name='eco_elec_energy_index')),
                ('non_elec_energy_index', models.IntegerField(default=0, verbose_name='non_elec_energy_index')),
                ('oil_energy_index', models.IntegerField(default=0, verbose_name='oil_energy_index')),
                ('envi_score', models.IntegerField(default=0, verbose_name='envi_score')),
                ('water_envi_score', models.IntegerField(default=0, verbose_name='water_envi_score')),
                ('air_envi_score', models.IntegerField(default=0, verbose_name='air_envi_score')),
                ('soil_envi_score', models.IntegerField(default=0, verbose_name='soil_envi_score')),
                ('duty_tax_rate', models.IntegerField(default=0, verbose_name='duty_tax_rate')),
                ('income_tax_rate', models.IntegerField(default=0, verbose_name='income_tax_rate')),
                ('donation_total', models.IntegerField(default=0, verbose_name='donation_total')),
                ('ranking', models.IntegerField(default=6, verbose_name='ranking')),
                ('oil_traffic_score', models.IntegerField(default=0, verbose_name='oil_traffic_score')),
                ('elec_traffic_score', models.IntegerField(default=0, verbose_name='elec_traffic_score')),
                ('subsidy_score', models.IntegerField(default=0, verbose_name='subsidy_score')),
                ('import_total', models.IntegerField(default=0, verbose_name='import_total')),
                ('export_total', models.IntegerField(default=0, verbose_name='export_total')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='accounts.user', verbose_name='person_id')),
            ],
        ),
    ]
