# Generated by Django 4.0.6 on 2022-07-23 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_user_player_last_uptime_alter_user_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='player_last_uptime',
            field=models.TextField(default=datetime.datetime(2022, 7, 23, 23, 30, 48, 830236), verbose_name='recentaccess'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.TextField(default=datetime.datetime(2022, 7, 23, 23, 30, 48, 830344), verbose_name='recentupdate'),
        ),
    ]
