# Generated by Django 4.0.6 on 2022-07-24 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_user_player_last_uptime_alter_user_update_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='main_misson',
            new_name='main_mission',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sub_misson',
            new_name='sub_mission',
        ),
        migrations.AlterField(
            model_name='user',
            name='player_last_uptime',
            field=models.TextField(default=datetime.datetime(2022, 7, 24, 16, 55, 5, 284037), verbose_name='recentaccess'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.TextField(default=datetime.datetime(2022, 7, 24, 16, 55, 5, 284141), verbose_name='recentupdate'),
        ),
    ]
