# Generated by Django 4.0.6 on 2022-07-24 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_user_player_last_uptime_alter_user_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='player_last_uptime',
            field=models.TextField(default=datetime.datetime(2022, 7, 24, 22, 11, 34, 688393), verbose_name='recentaccess'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.TextField(default=datetime.datetime(2022, 7, 24, 22, 11, 34, 688579), verbose_name='recentupdate'),
        ),
    ]
